export const AboutObj = {
    id: 'about1',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Text',
    headline: 'The foundations of world-leading artificial intelligence',
    description: 'The University of Manchester’s new Centre for AI Fundamentals is a key component of a number of significant recent investments The University of Manchester has made into AI education, innovation and industrial collaboration.',
    buttonLabel: 'Learn More',
    btnclick: 'about2',
    imgStart: false,
    img: require('../../images/ai.jpg'),
    alt:'ai',
    dark: true,
    primary: true,
    darkText: false,
};

export const AboutObjTwo = {
    id: 'about2',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Text',
    headline: 'The foundations of world-leading artificial intelligence',
    description: 'We boldly focus on fundamental AI research, which includes probabilistic modelling, deep learning, reinforcement learning, causal modelling, human-in-the-loop ML, explainable AI, ethics, privacy and security.',
    buttonLabel: 'Learn More',
    btnclick: 'about3',
    imgStart: true,
    img: require('../../images/arm.jpg'),
    alt:'arm',
    dark: false,
    primary: false,
    darkText: true,
};

export const AboutObjThree = {
    id: 'about3',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Text',
    headline: 'The foundations of world-leading artificial intelligence',
    description: 'The fundamentals are in motion – in particular, deployment and collaboration with people are centrally important fundamental AI problems, not only post-hoc issues. We develop AI that works well with humans and in deployment.',
    buttonLabel: 'Learn More',
    btnclick: 'about4',
    imgStart: false,
    img: require('../../images/laptop.jpg'),
    alt:'laptop',
    dark: true,
    primary: true,
    darkText: false,
};

export const AboutObjFour = {
    id: 'about4',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Text',
    headline: 'The foundations of world-leading artificial intelligence',
    description: 'This centre brings together renowned academic expertise in AI with the latest research taking place across our growing institutes including The Institute for Data Science and AI (IDSAI) and The Christabel Pankhurst Institute and our partnerships with The Alan Turing Institute and the European Laboratory for Learning and Intelligent Systems (ELLIS).',
    buttonLabel: 'Back to Top',
    btnclick: 'about1',
    imgStart: true,
    img: require('../../images/work.jpg'),
    alt:'work',
    dark: false,
    primary: false,
    darkText: true,
};